#!/usr/bin/env python3
"""
Report generation CLI tool
"""
import argparse
import sys
import os
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from reporting.generator import get_report_generator


def main():
    parser = argparse.ArgumentParser(description='Generate reports from anomaly data')
    
    subparsers = parser.add_subparsers(dest='command', help='Command')
    
    # Generate report from CSV
    csv_parser = subparsers.add_parser('from-csv', help='Generate report from CSV file')
    csv_parser.add_argument('csv_file', help='Path to CSV file')
    csv_parser.add_argument('--anomalies', help='Path to anomalies JSON file')
    csv_parser.add_argument('--title', default='Anomaly Detection Report', help='Report title')
    csv_parser.add_argument('--output', help='Output file (optional)')
    
    # Generate sample report
    sample_parser = subparsers.add_parser('sample', help='Generate a sample report for testing')
    sample_parser.add_argument('--count', type=int, default=100, help='Number of sample records')
    
    # List reports
    subparsers.add_parser('list', help='List generated reports')
    
    args = parser.parse_args()
    
    generator = get_report_generator()
    
    if args.command == 'from-csv':
        print(f"Reading data from {args.csv_file}...")
        df = pd.read_csv(args.csv_file)
        
        anomalies = []
        if args.anomalies:
            import json
            with open(args.anomalies, 'r') as f:
                anomalies = json.load(f)
        
        metadata = {
            'Source File': args.csv_file,
            'Total Rows': len(df),
            'Columns': ', '.join(df.columns[:5]) + ('...' if len(df.columns) > 5 else '')
        }
        
        report_path = generator.generate_html_report(
            data=df,
            anomalies=anomalies,
            metadata=metadata,
            title=args.title
        )
        
        print(f"✅ Report generated: {report_path}")
        
    elif args.command == 'sample':
        print(f"Generating sample report with {args.count} records...")
        
        # Create sample data
        import random
        import numpy as np
        
        dates = [datetime.now() - timedelta(days=i) for i in range(args.count)]
        farms = [f"FARM-{random.randint(1,10):04d}" for _ in range(args.count)]
        animals = ['cattle', 'swine', 'poultry', 'sheep', 'goat']
        types = [random.choice(animals) for _ in range(args.count)]
        temperatures = [38.5 + random.uniform(-2, 2) for _ in range(args.count)]
        sick = [random.randint(0, 10) for _ in range(args.count)]
        total = [random.randint(50, 200) for _ in range(args.count)]
        
        df = pd.DataFrame({
            'timestamp': dates,
            'farm_id': farms,
            'animal_type': types,
            'temperature': temperatures,
            'sick_animals': sick,
            'total_animals': total
        })
        
        # Create sample anomalies (10% of data)
        anomalies = []
        anomaly_indices = random.sample(range(args.count), args.count // 10)
        for idx in anomaly_indices:
            anomalies.append({
                'timestamp': str(dates[idx]),
                'farm_id': farms[idx],
                'animal_type': types[idx],
                'severity': random.choice(['low', 'medium', 'high']),
                'score': random.uniform(0.7, 1.0),
                'description': f"Unusual pattern detected in {types[idx]} population"
            })
        
        metadata = {
            'Report Type': 'Sample Test',
            'Generated By': 'report_tool.py',
            'Sample Size': args.count
        }
        
        report_path = generator.generate_html_report(
            data=df,
            anomalies=anomalies,
            metadata=metadata,
            title="Sample Anomaly Detection Report"
        )
        
        print(f"✅ Sample report generated: {report_path}")
        
    elif args.command == 'list':
        reports_dir = Path("outputs/reports")
        if reports_dir.exists():
            reports = list(reports_dir.glob("*.html"))
            print(f"\n📊 Generated Reports ({len(reports)}):")
            for report in sorted(reports, key=lambda x: x.stat().st_mtime, reverse=True):
                size = report.stat().st_size / 1024  # KB
                modified = datetime.fromtimestamp(report.stat().st_mtime)
                print(f"  {report.name} ({size:.1f} KB) - {modified.strftime('%Y-%m-%d %H:%M')}")
        else:
            print("No reports found.")
    
    else:
        parser.print_help()


if __name__ == "__main__":
    main()